"""Generated by ai-test-harness for python-jose 3.4.0 (category: unit).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import pytest
from jose import jwt, jwe, jws, JWTError, JWSError, JWSSignatureError, ExpiredSignatureError
from jose.constants import Algorithms
from jose.utils import base64url_encode, base64url_decode, ensure_binary, timedelta_total_seconds
import datetime
SECRET = b'test-secret-key-for-hs256'

def test_jwt_encode_decode_roundtrip():
    """jwt.encode then jwt.decode returns the original claims."""
    claims = {'sub': 'user1', 'name': 'Alice', 'custom': 42}
    token = jwt.encode(claims, SECRET, algorithm='HS256')
    decoded = jwt.decode(token, SECRET, algorithms=['HS256'])
    assert decoded == claims

def test_jwt_decode_wrong_key_raises_jwt_error():
    """jwt.decode with a wrong key raises JWTError."""
    token = jwt.encode({'sub': 'user1'}, SECRET, algorithm='HS256')
    with pytest.raises(JWTError):
        jwt.decode(token, b'wrong-key', algorithms=['HS256'])

def test_jwt_get_unverified_header_returns_alg():
    """jwt.get_unverified_header returns the algorithm from the token header."""
    token = jwt.encode({'sub': 'user1'}, SECRET, algorithm='HS256')
    header = jwt.get_unverified_header(token)
    assert header['alg'] == 'HS256'

def test_jwt_get_unverified_claims_returns_claims():
    """jwt.get_unverified_claims returns the claims without verification."""
    claims = {'sub': 'user1', 'data': 'hello'}
    token = jwt.encode(claims, SECRET, algorithm='HS256')
    unverified = jwt.get_unverified_claims(token)
    assert unverified == claims

def test_jwt_expired_token_raises_expired_signature_error():
    """jwt.decode raises ExpiredSignatureError for an expired token."""
    past = datetime.datetime(2020, 1, 1, tzinfo=datetime.timezone.utc)
    token = jwt.encode({'sub': 'user1', 'exp': past}, SECRET, algorithm='HS256')
    with pytest.raises(ExpiredSignatureError):
        jwt.decode(token, SECRET, algorithms=['HS256'])

def test_jws_sign_verify_roundtrip():
    """jws.sign then jws.verify returns the original payload."""
    payload = b'hello world'
    token = jws.sign(payload, SECRET, algorithm='HS256')
    verified = jws.verify(token, SECRET, ['HS256'])
    assert verified == payload

def test_jws_get_unverified_header_returns_alg():
    """jws.get_unverified_header returns the algorithm from the JWS header."""
    token = jws.sign(b'payload', SECRET, algorithm='HS256')
    header = jws.get_unverified_header(token)
    assert header['alg'] == 'HS256'

def test_base64url_encode_decode_roundtrip():
    """base64url_encode then base64url_decode returns the original bytes."""
    data = b'test data \x00\x01\x02'
    encoded = base64url_encode(data)
    decoded = base64url_decode(encoded)
    assert decoded == data

def test_ensure_binary_converts_str_to_bytes():
    """ensure_binary converts a string to its UTF-8 bytes."""
    result = ensure_binary('hello')
    assert result == b'hello'

def test_timedelta_total_seconds_returns_float():
    """timedelta_total_seconds returns the total seconds as a float."""
    delta = datetime.timedelta(hours=1, minutes=30)
    result = timedelta_total_seconds(delta)
    assert result == 5400.0
