// Generated by ai-test-harness (agent mode) for github.com/getkin/kin-openapi v0.139.0 (category: cve, issue CVE-2026-77354).
// Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
package harnesstest

import (
	"context"
	"net/http"
	"strings"
	"testing"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3filter"
)

// Test_GHSA_xhj3_7xw9_vr34_fix_pinning: a deepObject query parameter with a huge array index must not force an outsized allocation; the fixed decoder returns an error instead of allocating.
func Test_GHSA_xhj3_7xw9_vr34_fix_pinning(t *testing.T) {
	spec := `{"openapi":"3.0.0","info":{"title":"t","version":"1"},"paths":{"/p":{"get":{"parameters":[{"name":"q","in":"query","style":"deepObject","explode":true,"schema":{"type":"object","properties":{"a":{"type":"array","items":{"type":"string"}}}}}],"responses":{"200":{"description":"ok"}}}}}}`
	doc, err := openapi3.NewLoader().LoadFromData([]byte(spec))
	if err != nil { t.Fatalf("load spec: %v", err) }

	req, err := http.NewRequest("GET", "http://example.com/p?"+strings.Repeat("q[a][999999999]=x", 1), nil)
	if err != nil { t.Fatalf("new request: %v", err) }

	route := &openapi3filter.Route{Path: "/p", PathItem: doc.Paths.Find("/p")}

	done := make(chan error, 1)
	go func() { done <- openapi3filter.ValidateRequest(context.Background(), &openapi3filter.RequestValidationInput{Request: req, Route: route}) }()

	select {
	case err := <-done:
		if err == nil { t.Fatal("expected an error for sparse deepObject array index, got nil") } else { t.Logf("got expected error: %v", err) }
	}
}

// Test_GHSA_xhj3_7xw9_vr34_exposure: same trigger through the application's ValidateRequest call pattern with a Route. 
func Test_GHSA_xhj3_7xw9_vr34_exposure(t *testing.T) {
	spec := `{"openapi":"3.0.0","info":{"title":"t","version":"1"},"paths":{"/p":{"get":{"parameters":[{"name":"q","in":"query","style":"deepObject","explode":true,"schema":{"type":"object","properties":{"a":{"type":"array","items":{"type":"string"}}}}}],"responses":{"200":{"description":"ok"}}}}}}`
	doc, err := openapi3.NewLoader().LoadFromData([]byte(spec))
	if err != nil { t.Fatalf("load spec: %v", err) }

	req, _ := http.NewRequest("GET", "http://example.com/p?"+strings.Repeat("q[a][888888888]=y", 1), nil)
	route := &openapi3filter.Route{Path: "/p", PathItem: doc.Paths.Find("/p")}

	done := make(chan error, 1)
	go func() { done <- openapi3filter.ValidateRequest(context.Background(), &openapi3filter.RequestValidationInput{Request: req, Route: route}) }()

	select {
	case err := <-done:
		if err == nil { t.Fatal("expected an error for sparse deepObject array index via app call pattern, got nil") } else { t.Logf("got expected error: %v", err) }
	}
}
