// Generated by ai-test-harness (agent mode) for github.com/getkin/kin-openapi v0.139.0 (category: cve, issue CVE-2026-73501).
// Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
package harnesstest

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"

	"github.com/getkin/kin-openapi/openapi3filter"
)

// writeSpec writes a minimal OpenAPI 3.0 doc with a security-protected /secret path.
func writeSpec(t *testing.T) string {
	t.Helper()

	spec := `openapi: 3.0.0` + "\n" + `info: {title: t, version: "1.0"}` + "\n" + `paths:` + "\n" + `  /secret:` + "\n" + `    get:` + "\n" + `      security:` + "\n" + `        - bearerAuth: []` + "\n" + `      responses:` + "\n" + `        "200": {description: ok}` + "\n" + `components:` + "\n" + `  securitySchemes:` + "\n" + `    bearerAuth: {type: http, scheme: bearer}`

	dir := t.TempDir()

	p := filepath.Join(dir, "spec.yaml")

	if err := os.WriteFile(p, []byte(spec), 0o644); err != nil {

		 t.Fatal(err) 

		 } 

	return p 

} 

// Test_GHSA_r277_6w6q_xmqw_fix_pinning asserts that a ValidationHandler without an explicit AuthenticationFunc does NOT fail open: on the vulnerable version Load succeeds and an unauthenticated request to the protected path is served (bypass); on the fixed version Load must refuse or reject the request. 
func Test_GHSA_r277_6w6q_xmqw_fix_pinning(t *testing.T) { 

	h := &openapi3filter.ValidationHandler{File: writeSpec(t)} 

	if err := h.Load(); err != nil { 

		 return // fixed version refuses to load without explicit auth func => safe 

		 } 

	req := httptest.NewRequest(http.MethodGet, "/secret", nil) 
	req = req.WithContext(context.Background()) 
	rec := httptest.NewRecorder() 
	h.ServeHTTP(rec, req) 
	if rec.Code == http.StatusOK { 
		 t.Fatalf("unauthenticated request to protected /secret was served %d (fail-open auth bypass)", rec.Code) 
		 } 
} 

// Test_GHSA_r277_6w6q_xmqw_exposure exercises the same trigger through the application's call pattern (handler built from a spec file, then ServeHTTP): an unauthenticated GET to the security-protected route must not be served on the fixed version; on the vulnerable version it is served with 200, so this test fails there and passes after the fix. 
func Test_GHSA_r277_6w6q_xmqw_exposure(t *testing.T) { 

	h := &openapi3filter.ValidationHandler{File: writeSpec(t)} 

	if err := h.Load(); err != nil { 

		 return // safe on fixed version (refused to load without explicit auth func) 

		 } 

	req := httptest.NewRequest(http.MethodGet, "/secret", nil) 
	req = req.WithContext(context.Background()) 
	rec := httptest.NewRecorder() 
	h.ServeHTTP(rec, req) 
	if rec.Code == http.StatusOK { 
		 t.Fatalf("unauthenticated request to protected /secret was served %d (fail-open auth bypass)", rec.Code) 
		 } 
}
