"""Generated by ai-test-harness (agent mode) for python-jose 3.4.0 (category: cve, issue CVE-2024-33664).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import base64
import json
import zlib

import pytest

from jose import jwe
from jose.exceptions import JWEError


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _make_bomb_jwe(key: str) -> str:
    """Build a dir/A128GCM JWE whose zip=DEF payload decompresses to ~100MB."""
    header = {"alg": "dir", "enc": "A128GCM", "zip": "DEF"}
    encoded_header = _b64url(json.dumps(header).encode("utf-8"))
    compressed = zlib.compress(b"A" * (100 * 1024 * 1024))
    token = jwe.encrypt(compressed, key, algorithm="dir", encryption="A128GCM")
    parts = token.split(".")
    parts[3] = _b64url(compressed)
    return ".".join(parts)


def test_ghsa_cjwg_qfpm_7377_fix_pinning():
    """A compressed JWE bomb must be rejected instead of decompressing ~100MB."""
    key = "asecret128bitkey"
    token = _make_bomb_jwe(key)
    with pytest.raises(JWEError):
        jwe.decrypt(token, key)


def test_ghsa_cjwg_qfpm_7377_exposure():
    """Same bomb via the app's jwe.decrypt call pattern must raise JWEError."""
    key = "asecret128bitkey"
    token = _make_bomb_jwe(key)
    with pytest.raises(JWEError):
        jwe.decrypt(token, key)
