"""Generated by ai-test-harness (agent mode) for python-jose 3.4.0 (category: cve, issue CVE-2024-33663).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import base64

import pytest
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization

import jose
from jose import jwt
from jose.exceptions import JWKError


def _ssh_ecdsa_pem():
    # OpenSSH-style ECDSA public key whose base64 blob embeds a PEM header,
    # so the old substring check misses it while the new is_pem_format catches it.
    blob = base64.b64encode(b"-----BEGIN PUBLIC KEY-----")
    return b"ecdsa-sha2-nistp256 " + blob + b" user@host"


def test_ghsa_6c5p_j8vq_pqhj_fix_pinning():
    """OpenSSH ECDSA key used as HMAC secret must be rejected (CVE-2024-33663)."""
    with pytest.raises(JWKError):
        jwt.encode({"a": 1}, _ssh_ecdsa_pem(), algorithm="HS256")


def test_ghsa_6c5p_j8vq_pqhj_exposure():
    """App call pattern: jwt.decode with an OpenSSH ECDSA key as the HMAC secret must raise JWTError."""
    token = jwt.encode({"a": 1}, b"legit-hmac-secret-0123456789", algorithm="HS256")
    with pytest.raises(jose.JWTError):
        jwt.decode(token, _ssh_ecdsa_pem(), algorithms=["HS256"])
