"""Generated by ai-test-harness (agent mode) for python-jose 3.4.0 (category: cve, issue CVE-2024-29370).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import zlib

import pytest
from jose import jwe
from jose.exceptions import JWEError

KEY = "asecret128bitkey"


def _b64url(data: bytes) -> str:
    import base64
    return base64.urlsafe_b64encode(data).decode("ascii").rstrip("=")


def _make_token():
    """Build a valid dir/A128GCM JWE whose zip=DEF payload decompresses to 1 MiB."""
    header = _b64url(b'{"alg":"dir","enc":"A128GCM","zip":"DEF"}')
    big = b"A" * (1024 * 1024)
    token = jwe.encrypt(zlib.compress(big), KEY, algorithm="dir", encryption="A128GCM")
    parts = token.split(".")
    assert len(parts) == 5
    return ".".join([header, parts[1], parts[2], parts[3], parts[4]])


def test_pysec_2025_185_fix_pinning():
    """jwe.decrypt must reject a compressed JWE whose plaintext exceeds the size limit (CVE-2024-29370)."""
    token = _make_token()
    with pytest.raises(JWEError):
        jwe.decrypt(token, KEY)


def test_pysec_2025_185_exposure():
    """App-style jwe.decrypt call on an attacker-supplied compressed token must raise JWEError, not decompress unbounded data."""
    token = _make_token()
    with pytest.raises(JWEError):
        jwe.decrypt(token, KEY)
