"""Generated by ai-test-harness for python-jose 3.4.0 (category: cve).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import base64
import json
import zlib

import pytest
from jose import jwt
from jose.constants import Algorithms
from jose.exceptions import JOSEError
from jose.utils import base64url_decode, base64url_encode


def _b64url(data: bytes) -> str:
    return base64url_encode(data).decode("ascii")


def _make_jwt_bomb_token() -> str:
    """Build a JWE compact token whose compressed payload expands to ~100 MB."""
    # 100_000_000 bytes of 'A' compress to a tiny blob with zlib.
    compressed = zlib.compress(b"A" * 100_000_000, level=9)
    header = {"alg": "dir", "enc": "A256GCM", "zip": "DEF"}
    protected = _b64url(json.dumps(header).encode("utf-8"))
    # JWE compact: protected . encrypted_key . iv . ciphertext . tag
    # For 'dir' the encrypted_key is empty; iv/tag are arbitrary here since
    # the vulnerable code path decompresses before authentication.
    iv = _b64url(b"\x00" * 12)
    tag = _b64url(b"\x00" * 16)
    return ".".join([protected, "", iv, _b64url(compressed), tag])


def test_pysec_2024_233_fix_pinning():
    """Decoding a JWE token with a high-compression payload must raise, not expand."""
    token = _make_jwt_bomb_token()
    with pytest.raises(JOSEError):
        jwt.decode(token, b"secret-key-for-testing", algorithms=[Algorithms.HS256])


def test_pysec_2024_233_exposure():
    """Application call pattern (jwt.decode with algorithms list) must reject the bomb."""
    token = _make_jwt_bomb_token()
    with pytest.raises(JOSEError):
        jwt.decode(token, b"app-secret", algorithms=[Algorithms.HS256])
