"""Generated by ai-test-harness for python-jose 3.4.0 (category: cve).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import pytest
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization
from jose import jwt, JWTError
from jose.constants import Algorithms


def _ecdsa_p256_key():
    key = ec.generate_private_key(ec.SECP256R1())
    return key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )


def test_pysec_2024_232_fix_pinning():
    """A token signed with an ECDSA key must not be accepted as HS256 (algorithm confusion)."""
    key = _ecdsa_p256_key()
    token = jwt.encode({"sub": "user"}, key, algorithm=Algorithms.ES256)
    with pytest.raises(JWTError):
        jwt.decode(token, key, algorithms=[Algorithms.HS256])


def test_pysec_2024_232_exposure():
    """Application call pattern: jwt.decode with a single allowed algorithm must reject confused tokens."""
    key = _ecdsa_p256_key()
    token = jwt.encode({"sub": "user"}, key, algorithm=Algorithms.ES256)
    with pytest.raises(JWTError):
        jwt.decode(token, key, algorithms=[Algorithms.HS256])
