"""Generated by ai-test-harness (agent mode) for python-jose 3.4.0 (category: cve, issue CVE-2024-33663).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import pytest
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization

from jose import jwt, jwk
from jose.constants import ALGORITHMS
from jose.exceptions import JWKError, JWSError


def _ec_keypair():
    key = ec.generate_private_key(ec.SECP256R1())
    pub_pem = key.public_key().public_bytes(
        serialization.Encoding.PEM,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    return key, pub_pem


def test_ghsa_6c5p_j8vq_pqhj_fix_pinning():
    """HMAC key construction must reject OpenSSH ECDSA public key material (old 3.3.0 accepts it)."""
    _, pub_pem = _ec_keypair()
    ssh_key = b"ecdsa-sha2-nistp256 " + pub_pem.replace(b"\n", b" ") + b" user@host"
    with pytest.raises(JWKError):
        jwk.construct(ssh_key, ALGORITHMS.HS256)


def test_ghsa_6c5p_j8vq_pqhj_exposure():
    """App call pattern: jwt.encode with an SSH ECDSA key as the HMAC secret must raise a JWK/JWS error."""
    _, pub_pem = _ec_keypair()
    ssh_key = b"ecdsa-sha2-nistp256 " + pub_pem.replace(b"\n", b" ") + b" user@host"
    with pytest.raises((JWKError, JWSError)):
        jwt.encode({"sub": "test"}, ssh_key, algorithm=ALGORITHMS.HS256)
