"""Generated by ai-test-harness (agent mode) for python-jose 3.4.0 (category: cve, issue CVE-2024-33664).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import base64
import json
import zlib

import pytest

from jose import jwe
from jose.exceptions import JWEError


def _b64url(data):
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _make_bomb_jwe():
    """Build a valid DIR/A256GCM JWE whose zip=DEF payload decompresses to ~10MB."""
    key = b"0" * 32
    header = json.dumps({"alg": "dir", "enc": "A256GCM", "zip": "DEF"}).encode()
    compressed = zlib.compress(b"A" * (10 * 1024 * 1024))
    iv = b"\x00" * 12
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    aes = AESGCM(key)
    ct = aes.encrypt(iv, compressed, header)
    return ".".join([
        _b64url(header),
        _b64url(b""),
        _b64url(iv),
        _b64url(ct[:-16]),
        _b64url(ct[-16:]),
    ])


def test_ghsa_cjwg_qfpm_7377_fix_pinning():
    """jwe.decrypt must reject a compressed JWE whose decompressed size exceeds the limit."""
    token = _make_bomb_jwe()
    try:
        result = jwe.decrypt(token, b"0" * 32)
    except JWEError:
        return
    # Old (vulnerable) version: no size limit, bomb decompresses fully.
    assert result is None or len(result) <= 250 * 1024, (
        "vulnerable behavior: bomb decompressed to %r bytes" % (len(result) if result else 0)
    )


def test_ghsa_cjwg_qfpm_7377_exposure():
    """App-style jwe.decrypt(token, key) on a bomb token must raise JWEError, not return 10MB."""
    token = _make_bomb_jwe()
    try:
        result = jwe.decrypt(token, "0" * 32)
    except JWEError:
        return
    assert result is None or len(result) <= 250 * 1024, (
        "vulnerable behavior: bomb decompressed to %r bytes" % (len(result) if result else 0)
    )
