"""Generated by ai-test-harness for python-jose 3.4.0 (category: unit).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import time
import pytest
from jose import JWTError, jwt, jwe, jws, jwk, constants, exceptions, utils

def test_jwt_encode_decode_roundtrip_hs256():
    """jwt.encode then jwt.decode with HS256 returns the original claims."""
    key = b'secret-key-for-testing'
    claims = {'sub': '1234567890', 'name': 'Test User', 'iat': 1700000000}
    token = jwt.encode(claims, key, algorithm=constants.Algorithms.HS256)
    decoded = jwt.decode(token, key, algorithms=[constants.Algorithms.HS256])
    assert decoded == claims

def test_jwt_decode_wrong_key_raises_jwt_error():
    """jwt.decode with a wrong key raises JWTError."""
    token = jwt.encode({'sub': 'abc'}, b'correct-key', algorithm=constants.Algorithms.HS256)
    with pytest.raises(JWTError):
        jwt.decode(token, b'wrong-key', algorithms=[constants.Algorithms.HS256])

def test_jwt_get_unverified_header_returns_alg():
    """jwt.get_unverified_header returns the algorithm from the token header."""
    token = jwt.encode({'sub': 'x'}, b'key', algorithm=constants.Algorithms.HS256)
    header = jwt.get_unverified_header(token)
    assert header['alg'] == 'HS256'
    assert header['typ'] == 'JWT'

def test_jwt_decode_expired_token_raises_expired_signature_error():
    """jwt.decode raises ExpiredSignatureError when the token is expired."""
    key = b'secret'
    past = int(time.time()) - 3600
    token = jwt.encode({'exp': past}, key, algorithm=constants.Algorithms.HS256)
    with pytest.raises(exceptions.ExpiredSignatureError):
        jwt.decode(token, key, algorithms=[constants.Algorithms.HS256])

def test_jws_sign_verify_roundtrip():
    """jws.sign then jws.verify returns the original payload."""
    key = b'signing-key'
    payload = b'some payload data'
    token = jws.sign(payload, key, algorithm=constants.Algorithms.HS256)
    verified = jws.verify(token, key, algorithms=[constants.Algorithms.HS256])
    assert verified == payload

def test_jwk_construct_hmac_key():
    """jwk.construct creates a key object with the correct algorithm."""
    key_obj = jwk.construct(b'my-hmac-key', algorithm=constants.Algorithms.HS256)
    assert key_obj is not None
    assert key_obj._algorithm == constants.Algorithms.HS256

def test_utils_base64url_encode_decode_roundtrip():
    """utils.base64url_encode and base64url_decode are inverses."""
    data = b'test data \x00\x01\x02'
    encoded = utils.base64url_encode(data)
    decoded = utils.base64url_decode(encoded)
    assert decoded == data

def test_utils_ensure_binary():
    """utils.ensure_binary coerces str to bytes and leaves bytes unchanged."""
    assert utils.ensure_binary('hello') == b'hello'
    assert utils.ensure_binary(b'hello') == b'hello'
