"""Generated by ai-test-harness for python-jose 3.4.0 (category: cve).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
"""Tests for GHSA-cjwg-qfpm-7377 (CVE-2024-33664): JWE decompression bomb."""
import zlib

import pytest
from jose import jwe
from jose.exceptions import JWEError

# A key long enough for A256GCM (32 bytes)
_KEY = b"0123456789abcdef0123456789abcdef"


def _make_bomb_token() -> str:
    """Build a JWE compact token whose compressed payload expands past the limit."""
    # 300 KB of zeros compresses to a few hundred bytes
    plaintext = b"\x00" * (300 * 1024)
    return jwe.encrypt(plaintext, _KEY, encryption="A256GCM", algorithm="dir", zip="DEF")


def test_ghsa_cjwg_qfpm_7377_fix_pinning():
    """Decompressing a JWE whose payload exceeds the size limit raises JWEError."""
    token = _make_bomb_token()
    with pytest.raises(JWEError):
        jwe.decrypt(token, _KEY)


def test_ghsa_cjwg_qfpm_7377_exposure():
    """Application call pattern: jwe.decrypt on a bomb token raises JWEError, not OOM."""
    token = _make_bomb_token()
    with pytest.raises(JWEError):
        jwe.decrypt(token, _KEY)
