"""Generated by ai-test-harness for python-jose 3.4.0 (category: cve).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import pytest
from jose import jwt
from jose.exceptions import JWKError


def _ssh_ecdsa_key() -> bytes:
    return b"ecdsa-sha2-nistp256 AAAA"


def test_ghsa_6c5p_j8vq_pqhj_fix_pinning():
    """OpenSSH ECDSA key used as HMAC secret must be rejected (CVE-2024-33663)."""
    with pytest.raises(JWKError):
        jwt.encode({"sub": "x"}, _ssh_ecdsa_key(), algorithm="HS256")


def test_ghsa_6c5p_j8vq_pqhj_exposure():
    """App call pattern: jwt.decode with an OpenSSH ECDSA HMAC key must raise JWKError."""
    with pytest.raises(JWKError):
        jwt.decode("a.b.c", _ssh_ecdsa_key(), algorithms=["HS256"])
