"""Generated by ai-test-harness (agent mode) for python-jose 3.4.0 (category: cve, issue CVE-2024-33663).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import base64

import ecdsa
import pytest

from jose import jwt
from jose.constants import ALGORITHMS
from jose.exceptions import JWSError


def _ssh_ecdsa_key():
    sk = ecdsa.SigningKey.generate(curve=ecdsa.NIST256p)
    pub = sk.get_verifying_key()
    point = pub.to_string("uncompressed")
    return b"ecdsa-sha2-nistp256 " + base64.b64encode(point)


def test_ghsa_6c5p_j8vq_pqhj_fix_pinning():
    """OpenSSH ECDSA key must be rejected as an HMAC secret in 3.4.0 (accepted in 3.3.0)."""
    ssh_key = _ssh_ecdsa_key()
    with pytest.raises(JWSError):
        jwt.encode({"a": 1}, ssh_key, algorithm=ALGORITHMS.HS256)


def test_ghsa_6c5p_j8vq_pqhj_exposure():
    """App call pattern jwt.encode(payload, secret, algorithm=...) must reject OpenSSH ECDSA keys."""
    ssh_key = _ssh_ecdsa_key()
    with pytest.raises(JWSError):
        jwt.encode({"sub": "x"}, ssh_key, algorithm="HS256")
