// Generated by ai-test-harness (agent mode) for github.com/getkin/kin-openapi v0.139.0 (category: cve, issue CVE-2026-73502).
// Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
package harnesstest

import (
	"context"
	"net/http"
	"net/url"
	"testing"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3filter"
)

// Test_GHSA_jpcw_4wr7_c3vq_fix_pinning asserts that validating a request with a content parameter without schema does not panic on the fixed version.
func Test_GHSA_jpcw_4wr7_c3vq_fix_pinning(t *testing.T) {
	// Create a parameter with content but no schema
	parameter := &openapi3.Parameter{
		Name: "testParam",
		In:   "query",
		Content: openapi3.Content{
			"application/json": &openapi3.MediaType{},
		},
	}

	// Set up validation input
	req, err := http.NewRequest("GET", "http://example.com?testParam=value", nil)
	if err != nil {
		t.Fatalf("Failed to create request: %v", err)
	}
	input := &openapi3filter.RequestValidationInput{
		Request:    req,
		PathParams: map[string]string{},
		QueryParams: url.Values{
			"testParam": {"value"},
		},
	}

	// This should not panic on the fixed version (v0.144.0)
	err = openapi3filter.ValidateParameter(context.Background(), input, parameter)
	if err == nil {
		t.Errorf("Expected validation to fail due to missing schema, but it succeeded")
	}
}

// Test_GHSA_jpcw_4wr7_c3vq_exposure asserts the same behavior through the common application call pattern using ValidateRequest.
func Test_GHSA_jpcw_4wr7_c3vq_exposure(t *testing.T) {
	// Create a parameter with content but no schema
	parameter := &openapi3.Parameter{
		Name: "testParam",
		In:   "query",
		Content: openapi3.Content{
			"application/json": &openapi3.MediaType{},
		},
	}

	// Create a path item with the parameter
	pathItem := &openapi3.PathItem{
		Parameters: []*openapi3.ParameterRef{
			{Value: parameter},
		},
	}

	// Create a router and set up the route
	router := openapi3filter.NewRouter()
	router.AddRoute(&openapi3filter.Route{
		Path:   "/test",
		Method: "GET",
		PathItem: pathItem,
		Spec: &openapi3.T{},
	})

	// Set up validation input
	req, err := http.NewRequest("GET", "http://example.com/test?testParam=value", nil)
	if err != nil {
		t.Fatalf("Failed to create request: %v", err)
	}
	route, _ := router.FindRoute(req)
	input := &openapi3filter.RequestValidationInput{
		Request:    req,
		PathParams: map[string]string{},
		QueryParams: url.Values{
			"testParam": {"value"},
		},
		Route: route,
	}

	// This should not panic on the fixed version (v0.144.0)
	err = openapi3filter.ValidateRequest(context.Background(), input)
	if err == nil {
		t.Errorf("Expected validation to fail due to missing schema, but it succeeded")
	}
}