// Generated by ai-test-harness (agent mode) for github.com/getkin/kin-openapi v0.139.0 (category: cve, issue CVE-2026-77354).
// Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
package harnesstest

import (
	"context"
	"net/http"
	"testing"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3filter"
	"github.com/getkin/kin-openapi/routers/gorillamux"
)

func Test_GHSA_xhj3_7xw9_vr34_fix_pinning(t *testing.T) {
	// Assert that deepObject query parameter decoding does not cause uncontrolled resource consumption
	swagger := &openapi3.T{
		OpenAPI: "3.0.0",
		Info: &openapi3.Info{
			Title:   "Test API",
			Version: "1.0",
		},
		Paths: openapi3.NewPaths(),
	}

	pathItem := &openapi3.PathItem{
		Get: &openapi3.Operation{
			Parameters: openapi3.Parameters{
				&openapi3.ParameterRef{
					Value: &openapi3.Parameter{
						Name:     "data",
						In:       "query",
						Required: false,
						Style:    "deepObject",
						Explode:  true,
						Schema: &openapi3.SchemaRef{
							Value: openapi3.NewObjectSchema(),
						},
					},
				},
			},
		},
	}
	swagger.Paths.Set("/test", pathItem)

	// Create router and validator
	router, err := gorillamux.NewRouter(swagger)
	if err != nil {
		t.Fatal(err)
	}

	req, err := http.NewRequestWithContext(context.Background(), "GET", "http://localhost/test?data[key]=value&data[other]=value2", nil)
	if err != nil {
		t.Fatal(err)
	}

	route, _, err := router.FindRoute(req)
	if err != nil {
		t.Fatal(err)
	}

	input := &openapi3filter.RequestValidationInput{
		Request:    req,
		Route:      route,
		Parameters: openapi3.NewParameters(),
	}

	// This should not panic or consume excessive resources
	err = openapi3filter.ValidateRequest(context.Background(), input)
	if err != nil {
		t.Errorf("Expected no error, got %v", err)
	}
}

func Test_GHSA_xhj3_7xw9_vr34_exposure(t *testing.T) {
	// Same trigger through the application's call pattern
	swagger := &openapi3.T{
		OpenAPI: "3.0.0",
		Info: &openapi3.Info{
			Title:   "Test API",
			Version: "1.0",
		},
		Paths: openapi3.NewPaths(),
	}

	pathItem := &openapi3.PathItem{
		Get: &openapi3.Operation{
			Parameters: openapi3.Parameters{
				&openapi3.ParameterRef{
					Value: &openapi3.Parameter{
						Name:     "data",
						In:       "query",
						Required: false,
						Style:    "deepObject",
						Explode:  true,
						Schema: &openapi3.SchemaRef{
							Value: openapi3.NewObjectSchema(),
						},
					},
				},
			},
		},
	}
	swagger.Paths.Set("/test", pathItem)

	// Create router and validator
	router, err := gorillamux.NewRouter(swagger)
	if err != nil {
		t.Fatal(err)
	}

	req, err := http.NewRequestWithContext(context.Background(), "GET", "http://localhost/test?data[key]=value&data[other]=value2", nil)
	if err != nil {
		t.Fatal(err)
	}

	route, _, err := router.FindRoute(req)
	if err != nil {
		t.Fatal(err)
	}

	input := &openapi3filter.RequestValidationInput{
		Request:    req,
		Route:      route,
		Parameters: openapi3.NewParameters(),
	}

	// This should not panic or consume excessive resources
	err = openapi3filter.ValidateRequest(context.Background(), input)
	if err != nil {
		t.Errorf("Expected no error, got %v", err)
	}
}