"""Generated by ai-test-harness for python-jose 3.4.0 (category: unit).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import pytest
from jose import jwt, jwe, jws, jwk, utils, constants
from jose.exceptions import JOSEError, JWSError, JWSSignatureError, JWSAlgorithmError, JWTError, JWTClaimsError, ExpiredSignatureError, JWKError, JWEError, JWEParseError, JWEInvalidAuth, JWEAlgorithmUnsupportedError

def test_jwt_encode_decode_roundtrip():
    """jwt.encode with HS256 and jwt.decode with the same key returns the original claims."""
    key = 'secret-key-for-testing'
    claims = {'sub': '1234567890', 'name': 'John Doe', 'iat': 1516239022}
    token = jwt.encode(claims, key, algorithm='HS256')
    decoded = jwt.decode(token, key, algorithms=['HS256'])
    assert decoded['sub'] == '1234567890'
    assert decoded['name'] == 'John Doe'
    assert decoded['iat'] == 1516239022

def test_jwt_decode_wrong_key_raises_jwt_error():
    """jwt.decode with a different key than used for encoding raises JWTError."""
    token = jwt.encode({'sub': 'test'}, 'correct-key', algorithm='HS256')
    with pytest.raises(JWTError):
        jwt.decode(token, 'wrong-key', algorithms=['HS256'])

def test_jwt_get_unverified_header_returns_algorithm():
    """jwt.get_unverified_header returns the header dict including the algorithm."""
    token = jwt.encode({'sub': 'test'}, 'key', algorithm='HS256')
    header = jwt.get_unverified_header(token)
    assert header['alg'] == 'HS256'
    assert header['typ'] == 'JWT'

def test_jwt_decode_expired_token_raises_expired_signature_error():
    """jwt.decode raises ExpiredSignatureError when the token's exp claim is in the past."""
    token = jwt.encode({'sub': 'test', 'exp': 1000000000}, 'key', algorithm='HS256')
    with pytest.raises(ExpiredSignatureError):
        jwt.decode(token, 'key', algorithms=['HS256'])

def test_jwt_decode_invalid_token_raises_jwt_error():
    """jwt.decode raises JWTError for a malformed token string."""
    with pytest.raises(JWTError):
        jwt.decode('not-a-valid-jwt', 'key', algorithms=['HS256'])

def test_utils_base64url_encode_decode_roundtrip():
    """utils.base64url_encode and utils.base64url_decode are inverse operations."""
    data = b'Hello, World!'
    encoded = utils.base64url_encode(data)
    decoded = utils.base64url_decode(encoded)
    assert decoded == data
