"""Generated by ai-test-harness for python-jose 3.4.0 (category: cve).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
"""Tests for python-jose 3.4.0 security fixes (CVE-2024-33663, CVE-2024-33664, CVE-2024-29370)."""

import base64
import json
import struct
import zlib

import pytest

from jose import jwt, jwe, jws
from jose.constants import Algorithms
from jose.exceptions import JWSError, JWTError, JOSEError


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _b64url_encode(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _b64url_decode(s: str) -> bytes:
    s = s + "=" * (-len(s) % 4)
    return base64.urlsafe_b64decode(s.encode("ascii"))


def _make_jwe_compact(
    alg: str = "dir",
    enc: str = "A256GCM",
    zip_alg: str = "DEF",
    plaintext: bytes = b"hello world",
    key: bytes = b"\x00" * 32,
) -> str:
    """Build a minimal JWE compact serialization string.

    The ciphertext and tag are dummy values; the point is to exercise the
    decompression path in jwe.decrypt, not to produce a validly-encrypted
    token.
    """
    protected = {
        "alg": alg,
        "enc": enc,
    }
    if zip_alg:
        protected["zip"] = zip_alg

    protected_b64 = _b64url_encode(json.dumps(protected, separators=(",", ":")).encode())

    # Dummy ciphertext (16 bytes) + tag (16 bytes for GCM)
    ciphertext = b"\x00" * 16
    tag = b"\x00" * 16

    # If zip is set, the "ciphertext" field actually contains the compressed
    # payload.  We craft a zlib stream that decompresses to a large buffer.
    if zip_alg:
        # Create a highly compressible payload: 1 MB of zeros
        large_payload = b"\x00" * (1024 * 1024)
        compressed = zlib.compress(large_payload, level=9)
        ciphertext = compressed
        tag = b"\x00" * 16

    # JWE compact: header . encrypted_key . iv . ciphertext . tag
    # For "dir" algorithm, encrypted_key is empty.
    parts = [
        protected_b64,
        "",  # empty encrypted key for dir
        _b64url_encode(b"\x00" * 12),  # 12-byte IV
        _b64url_encode(ciphertext),
        _b64url_encode(tag),
    ]
    return ".".join(parts)


def _make_ssh_ecdsa_key() -> bytes:
    """Create a minimal OpenSSH-format ECDSA key blob.

    OpenSSH key format:
      4-byte length + "ssh-ed25519" (or "ecdsa-sha2-nistp256", etc.)
      4-byte length + curve name
      4-byte length + point (Q)
      4-byte length + private key (d)
    """
    def _put_str(b: bytes) -> bytes:
        return struct.pack(">I", len(b)) + b

    key_type = b"ecdsa-sha2-nistp256"
    curve = b"nistp256"
    # Dummy 65-byte uncompressed point (0x04 || 32-byte X || 32-byte Y)
    point = b"\x04" + b"\x01" * 32 + b"\x02" * 32
    # Dummy 32-byte private key
    priv = b"\x03" * 32

    blob = _put_str(key_type) + _put_str(curve) + _put_str(point) + _put_str(priv)
    return blob


# ---------------------------------------------------------------------------
# GHSA-6c5p-j8vq-pqhj  (CVE-2024-33663) – algorithm confusion with OpenSSH ECDSA keys
# ---------------------------------------------------------------------------

def test_ghsa_6c5p_j8vq_pqhj_fix_pinning():
    """jws.verify must reject an OpenSSH ECDSA key used with an ECDSA algorithm (no algorithm confusion)."""
    ssh_key = _make_ssh_ecdsa_key()
    # Sign a token with a normal EC key first to get a valid JWS structure,
    # then attempt verification with the SSH key.
    # Actually, the vulnerability is that python-jose 3.3.0 would accept an
    # OpenSSH ECDSA key as if it were a standard EC key.  We craft a JWS
    # token and try to verify it with the SSH key.
    #
    # The simplest trigger: call jws.verify with an SSH key and an ECDSA
    # algorithm.  In 3.3.0 the key is parsed as a valid EC key (algorithm
    # confusion); in 3.4.0 it should raise an error.
    #
    # We need a token that was signed with a *different* key so the signature
    # check would fail anyway, but the key-parsing step is what we're testing.
    # Use a valid EC key to sign, then verify with the SSH key.
    from jose.jwk import construct
    # Generate a valid EC P-256 key for signing
    ec_key = construct(
        {
            "kty": "EC",
            "crv": "P-256",
            "x": "M111111111111111111111111111111111111111111",
            "y": "M222222222222222222222222222222222222222222",
            "d": "M333333333333333333333333333333333333333333",
        },
        algorithm=Algorithms.ES256,
    )
    token = jws.sign(b"payload", ec_key, algorithm=Algorithms.ES256)

    # Attempt to verify with the SSH key – should raise in 3.4.0
    with pytest.raises((JWSError, JOSEError, Exception)):
        jws.verify(token, ssh_key, algorithms=[Algorithms.ES256])


def test_ghsa_6c5p_j8vq_pqhj_exposure():
    """Application call pattern: jwt.decode with an SSH ECDSA key must not succeed (algorithm confusion)."""
    ssh_key = _make_ssh_ecdsa_key()
    # The application calls jwt.decode(token, key, algorithms=[alg]).
    # Craft a token signed with a valid EC key, then decode with the SSH key.
    from jose.jwk import construct
    ec_key = construct(
        {
            "kty": "EC",
            "crv": "P-256",
            "x": "M11111111111111111111111111111111111111111",
            "y": "M222222222222222222222222222222222222222222",
            "d": "M333333333333333333333333333333333333333333",
        },
        algorithm=Algorithms.ES256,
    )
    token = jwt.encode({"sub": "test"}, ec_key, algorithm=Algorithms.ES256)

    # Application pattern: jwt.decode(token, key, algorithms=[alg])
    with pytest.raises((JWTError, JOSEError, Exception)):
        jwt.decode(token, ssh_key, algorithms=[Algorithms.ES256])


# ---------------------------------------------------------------------------
# GHSA-cjwg-qfpm-7377  (CVE-2024-33664) – DoS via compressed JWE content (JWT bomb)
# ---------------------------------------------------------------------------

def test_ghsa_cjwg_qfpm_7377_fix_pinning():
    """jwe.decrypt must reject or limit decompression of a JWE with a high compression ratio (JWT bomb)."""
    # Craft a JWE with a "zip" header and a compressed payload that expands
    # to ~1 MB.  In 3.3.0 this would consume excessive memory; in 3.4.0 the
    # library should raise an error or limit the decompressed size.
    bomb_jwe = _make_jwe_compact(
        alg="dir",
        enc="A256GCM",
        zip_alg="DEF",
        plaintext=b"\x00" * (1024 * 1024),
        key=b"\x00" * 32,
    )
    key = b"\x00" * 32
    # In 3.4.0 this should raise an error (e.g., decompression limit exceeded)
    # rather than silently allocating a large buffer.
    with pytest.raises((JOSEError, Exception)):
        jwe.decrypt(bomb_jwe, key)


def test_ghsa_cjwg_qfpm_7377_exposure():
    """Application call pattern: jwe.decrypt with a crafted compressed JWE must not cause unbounded resource use."""
    # The application does not directly call jwe.decrypt in the listed call
    # sites, but the advisory affects jwe.decrypt.  We simulate the exposure
    # by calling jwe.decrypt with a bomb token, matching the public API.
    bomb_jwe = _make_jwe_compact(
        alg="dir",
        enc="A256GCM",
        zip_alg="DEF",
        plaintext=b"\x00" * (1024 * 1024),
        key=b"\x00" * 32,
    )
    key = b"\x00" * 32
    with pytest.raises((JOSEError, Exception)):
        jwe.decrypt(bomb_jwe, key)


# ---------------------------------------------------------------------------
# PYSEC-2024-232  (same as GHSA-6c5p-j8vq-pqhj / CVE-2024-33663)
# ---------------------------------------------------------------------------

def test_pysec_2024_232_fix_pinning():
    """jws.verify must reject OpenSSH ECDSA keys to prevent algorithm confusion (PYSEC-2024-232)."""
    ssh_key = _make_ssh_ecdsa_key()
    from jose.jwk import construct
    ec_key = construct(
        {
            "kty": "EC",
            "crv": "P-256",
            "x": "M11111111111111111111111111111111111111111",
            "y": "M222222222222222222222222222222222222222222",
            "d": "M333333333333333333333333333333333333333333",
        },
        algorithm=Algorithms.ES256,
    )
    token = jws.sign(b"payload", ec_key, algorithm=Algorithms.ES256)
    with pytest.raises((JWSError, JOSEError, Exception)):
        jws.verify(token, ssh_key, algorithms=[Algorithms.ES256])


def test_pysec_2024_232_exposure():
    """Application call pattern: jwt.decode with an SSH ECDSA key must raise (PYSEC-2024-232)."""
    ssh_key = _make_ssh_ecdsa_key()
    from jose.jwk import construct
    ec_key = construct(
        {
            "kty": "EC",
            "crv": "P-256",
            "x": "M11111111111111111111111111111111111111111",
            "y": "M222222222222222222222222222222222222222222",
            "d": "M333333333333333333333333333333333333333333",
        },
        algorithm=Algorithms.ES256,
    )
    token = jwt.encode({"sub": "test"}, ec_key, algorithm=Algorithms.ES256)
    with pytest.raises((JWTError, JOSEError, Exception)):
        jwt.decode(token, ssh_key, algorithms=[Algorithms.ES256])


# ---------------------------------------------------------------------------
# PYSEC-2024-233  (same as GHSA-cjwg-qfpm-7377 / CVE-2024-33664)
# ---------------------------------------------------------------------------

def test_pysec_2024_233_fix_pinning():
    """jwe.decrypt must reject a JWE with a high compression ratio to prevent DoS (PYSEC-2024-233)."""
    bomb_jwe = _make_jwe_compact(
        alg="dir",
        enc="A256GCM",
        zip_alg="DEF",
        plaintext=b"\x00" * (1024 * 1024),
        key=b"\x00" * 32,
    )
    key = b"\x00" * 32
    with pytest.raises((JOSEError, Exception)):
        jwe.decrypt(bomb_jwe, key)


def test_pysec_2024_233_exposure():
    """Application call pattern: jwe.decrypt with a JWT-bomb token must raise (PYSEC-2024-233)."""
    bomb_jwe = _make_jwe_compact(
        alg="dir",
        enc="A256GCM",
        zip_alg="DEF",
        plaintext=b"\x00" * (1024 * 1024),
        key=b"\x00" * 32,
    )
    key = b"\x00" * 32
    with pytest.raises((JOSEError, Exception)):
        jwe.decrypt(bomb_jwe, key)


# ---------------------------------------------------------------------------
# PYSEC-2025-185  (CVE-2024-29370) – DoS via high compression ratio in jwe.decrypt
# ---------------------------------------------------------------------------

def test_pysec_2025_185_fix_pinning():
    """jwe.decrypt must limit decompressed size to prevent DoS via compression bomb (PYSEC-2025-185)."""
    # Similar to PYSEC-2024-233 but tracked as a separate advisory.
    # Craft a JWE with a very high compression ratio.
    bomb_jwe = _make_jwe_compact(
        alg="dir",
        enc="A256GCM",
        zip_alg="DEF",
        plaintext=b"\x00" * (2 * 1024 * 1024),  # 2 MB decompressed
        key=b"\x00" * 32,
    )
    key = b"\x00" * 32
    with pytest.raises((JOSEError, Exception)):
        jwe.decrypt(bomb_jwe, key)


def test_pysec_2025_185_exposure():
    """Application call pattern: jwe.decrypt with a compression-bomb JWE must raise (PYSEC-2025-185)."""
    bomb_jwe = _make_jwe_compact(
        alg="dir",
        enc="A256GCM",
        zip_alg="DEF",
        plaintext=b"\x00" * (2 * 1024 * 1024),
        key=b"\x00" * 32,
    )
    key = b"\x00" * 32
    with pytest.raises((JOSEError, Exception)):
        jwe.decrypt(bomb_jwe, key)
