"""Generated by ai-test-harness (agent mode) for python-jose 3.4.0 (category: cve, issue CVE-2024-29370).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import base64
import json

import pytest

from jose import jwe
from jose.exceptions import JWEError


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _make_token(plaintext: bytes, key: str, zip_alg: str) -> str:
    """Build a valid JWE compact token with the given zip header."""
    header = {"alg": "dir", "enc": "A256GCM", "zip": zip_alg}
    protected = _b64url(json.dumps(header).encode("utf-8"))
    cek = key.encode("utf-8") * 2  # 32-byte CEK for A256GCM
    iv = b"\x01" * 12
    aad = protected.encode("ascii")

    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    ct_and_tag = AESGCM(cek).encrypt(iv, plaintext, aad)
    ciphertext, tag = ct_and_tag[:-16], ct_and_tag[-16:]

    parts = [protected, "", _b64url(iv), _b64url(ciphertext), _b64url(tag)]
    return ".".join(parts)


def test_pysec_2025_185_fix_pinning():
    """jwe.decrypt must reject a compressed JWE whose decompressed size exceeds the limit (CVE-2024-33664 DoS)."""
    plaintext = b"A" * (1024 * 1024)  # decompresses to ~1 MiB, over the 250 KiB limit
    token = _make_token(plaintext, "asecret128bitkey", "DEF")

    with pytest.raises(JWEError):
        jwe.decrypt(token, "asecret128bitkey")


def test_pysec_2025_185_exposure():
    """Same oversized-compression trigger through the app's direct jwe.decrypt(jwe_str, key) call pattern."""
    plaintext = b"B" * (512 * 1024)  # decompressed size > 250 KiB limit; token itself is tiny
    token = _make_token(plaintext, "anothersecretkey", "DEF")

    with pytest.raises(JWEError):
        jwe.decrypt(token, "anothersecretkey")
