"""Generated by ai-test-harness (agent mode) for python-jose 3.4.0 (category: cve, issue CVE-2024-29370).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import pytest
from jose import jwe, constants
from jose.exceptions import JWEError

def test_pysec_2025_185_fix_pinning():
    """Assert that oversized JWE tokens are rejected to prevent DoS."""
    # Create a small payload
    plaintext = b"Hello, World!"
    # Use 32-byte key for A256GCM
    key = b"01234567890123456789012345678901"
    
    # Encrypt with compression
    jwe_token = jwe.encrypt(plaintext, key, zip=constants.Zips.DEF)
    
    # Create a malicious JWE by appending garbage to exceed size limit
    oversized_token = jwe_token + b"A" * (constants.JWE_SIZE_LIMIT + 1)
    
    # This should fail with JWEError due to size check
    with pytest.raises(JWEError):
        jwe.decrypt(oversized_token, key)

def test_pysec_2025_185_exposure():
    """Same trigger through application call pattern."""
    # Same as above but ensure we use only symbols from both versions
    plaintext = b"Hello, World!"
    key = b"01234567890123456789012345678901"
    
    jwe_token = jwe.encrypt(plaintext, key, zip="DEF")
    oversized_token = jwe_token + b"A" * (250 * 1024 + 1)  # Direct constant use
    
    with pytest.raises(JWEError):
        jwe.decrypt(oversized_token, key)
