// Generated by ai-test-harness (agent mode) for github.com/getkin/kin-openapi v0.139.0 (category: cve, issue CVE-2026-77354).
// Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
package harnesstest

import (
	"context"
	"net/http"
	"net/url"
	"testing"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3filter"
)

func Test_GHSA_xhj3_7xw9_vr34_fix_pinning(t *testing.T) {
	// Assert that deepObject query parameter decoding does not cause uncontrolled resource consumption
	spec := &openapi3.T{}
	spec.Paths = make(map[string]*openapi3.PathItem)
	operation := &openapi3.Operation{}
	param := &openapi3.Parameter{
		Name: "param",
		In:   "query",
		Style: "deepObject",
	}
	ptrExplode := true
	param.Explode = &ptrExplode
	param.Schema = &openapi3.SchemaRef{
		Value: openapi3.NewObjectSchema(),
	}
	operation.Parameters = &openapi3.Parameters{
		&openapi3.ParameterRef{Value: param},
	}
	spec.Paths["/test"] = &openapi3.PathItem{Get: operation}

	// Create a large query string with deepObject style
	values := url.Values{}
	for i := 0; i < 1000; i++ {
		values.Add("param[deep][key]", "value")
	}

	req := &http.Request{
		Method: "GET",
		URL: &url.URL{
			Path:     "/test",
			RawQuery: values.Encode(),
		},
		Header: http.Header{},
	}

	input := &openapi3filter.RequestValidationInput{
		Request:    req,
		PathParams: map[string]string{},
		Options:    &openapi3filter.Options{},
	}

	// This should not panic or consume excessive resources
	err := openapi3filter.ValidateRequest(context.Background(), input)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
}

func Test_GHSA_xhj3_7xw9_vr34_exposure(t *testing.T) {
	// Test the same vulnerability through the application's call pattern
	spec := &openapi3.T{}
	spec.Paths = make(map[string]*openapi3.PathItem)
	operation := &openapi3.Operation{}
	param := &openapi3.Parameter{
		Name: "param",
		In:   "query",
		Style: "deepObject",
	}
	ptrExplode := true
	param.Explode = &ptrExplode
	param.Schema = &openapi3.SchemaRef{
		Value: openapi3.NewObjectSchema(),
	}
	operation.Parameters = &openapi3.Parameters{
		&openapi3.ParameterRef{Value: param},
	}
	spec.Paths["/test"] = &openapi3.PathItem{Get: operation}

	// Create a large query string with deepObject style
	values := url.Values{}
	for i := 0; i < 1000; i++ {
		values.Add("param[deep][key]", "value")
	}

	req := &http.Request{
		Method: "GET",
		URL: &url.URL{
			Path:     "/test",
			RawQuery: values.Encode(),
		},
		Header: http.Header{},
	}

	// Use the same validation pattern as seen in the application
	input := &openapi3filter.RequestValidationInput{
		Request:    req,
		PathParams: map[string]string{},
		Options:    &openapi3filter.Options{},
	}

	err := openapi3filter.ValidateRequest(context.Background(), input)
	if err != nil {
		t.Fatalf("Expected no error, got %v", err)
	}
}