// Generated by ai-test-harness (agent mode) for github.com/getkin/kin-openapi v0.139.0 (category: cve, issue CVE-2026-73502).
// Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
package harnesstest

import (
	"context"
	"net/http"
	"strings"
	"testing"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3filter"
	"github.com/stretchr/testify/assert"
)

func Test_GHSA_jpcw_4wr7_c3vq_fix_pinning(t *testing.T) {
	// Assert that ValidateRequest does not panic when validating a request with a content parameter without schema
	spec := &openapi3.T{
		Paths: openapi3.NewPaths(),
	}
	pathItem := &openapi3.PathItem{
		Post: &openapi3.Operation{
			RequestBody: &openapi3.RequestBodyRef{
				Value: &openapi3.RequestBody{
					Content: openapi3.Content{
						"application/json": &openapi3.MediaType{
							Schema: nil, // No schema defined
						},
					},
				},
			},
		},
	}
	spec.Paths.Set("/test", pathItem)

	ctx := context.Background()
	req, err := http.NewRequestWithContext(ctx, "POST", "http://localhost/test", strings.NewReader(`{}`))
	assert.NoError(t, err)
	req.Header.Set("Content-Type", "application/json")

	// Create router and find route
	router, _ := openapi3filter.NewRouter(spec)
	route, pathParams, _ := router.FindRoute(req)

	// Create validation input
	input := &openapi3filter.RequestValidationInput{
		Request:    req,
		PathParams: pathParams,
		Route:      route,
		Options:    &openapi3filter.Options{},
	}

	// This should not panic in the fixed version (v0.144.0) and should return an error in the vulnerable version (v0.139.0)
	err = openapi3filter.ValidateRequest(ctx, input)
	assert.Error(t, err)
}

func Test_GHSA_jpcw_4wr7_c3vq_exposure(t *testing.T) {
	// Assert the same behavior through the application's call pattern using ValidationHandler
	spec := &openapi3.T{
		Paths: openapi3.NewPaths(),
	}
	pathItem := &openapi3.PathItem{
		Post: &openapi3.Operation{
			RequestBody: &openapi3.RequestBodyRef{
				Value: &openapi3.RequestBody{
					Content: openapi3.Content{
						"application/json": &openapi3.MediaType{
							Schema: nil, // No schema defined
						},
					},
				},
			},
		},
	}
	spec.Paths.Set("/test", pathItem)

	ctx := context.Background()
	req, err := http.NewRequestWithContext(ctx, "POST", "http://localhost/test", strings.NewReader(`{}`))
	assert.NoError(t, err)
	req.Header.Set("Content-Type", "application/json")

	handler := &openapi3filter.ValidationHandler{
		Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusOK)
		}),
		AuthenticationFunc: func(ctx context.Context, input *openapi3filter.AuthenticationInput) error {
			return nil
		},
	}

	// Create router and set it on the handler
	router, _ := openapi3filter.NewRouter(spec)
	handler.router = router

	recorder := &mockResponseWriter{}

	// This should not panic in the fixed version (v0.144.0) and should return an error in the vulnerable version (v0.139.0)
	handler.ServeHTTP(recorder, req)

	assert.True(t, recorder.called)
}

type mockResponseWriter struct {
	called bool
}

func (m *mockResponseWriter) Header() http.Header {
	return http.Header{}
}

func (m *mockResponseWriter) Write(b []byte) (int, error) {
	m.called = true
	return len(b), nil
}

func (m *mockResponseWriter) WriteHeader(statusCode int) {
	m.called = true
}