// Generated by ai-test-harness (agent mode) for github.com/getkin/kin-openapi v0.139.0 (category: cve, issue CVE-2026-76905).
// Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
package harnesstest

import (
	"context"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3filter"
)

func Test_GHSA_mmfr_pmjx_hw9w_fix_pinning(t *testing.T) {
	// Assert that malformed multipart/form-data does not cause a nil-pointer panic in ConvertErrors
	spec := &openapi3.T{
		Paths: openapi3.Paths{
			"/test": &openapi3.PathItem{
				Post: &openapi3.Operation{
					RequestBody: &openapi3.RequestBodyRef{
						Value: &openapi3.RequestBody{
							Content: openapi3.Content{
								"multipart/form-data": {
									Schema: &openapi3.SchemaRef{
										Value: openapi3.NewSchemaRef("", &openapi3.Schema{Type: "object"}),
									},
								},
							},
						},
					},
				},
			},
		},
	}

	req := httptest.NewRequest("POST", "http://example.com/test", strings.NewReader("--boundary\r\nmalformed"))
	req.Header.Set("Content-Type", "multipart/form-data; boundary=boundary")

	err := openapi3filter.ValidateRequest(context.Background(), &openapi3filter.RequestValidationInput{
		Request: req,
		Path:    "/test",
		Method:  "POST",
		Spec:    spec,
		Body:    nil,
		Params:  openapi3.Parameters{},
	})

	if err == nil {
		t.Fatalf("expected error from malformed multipart/form-data, got nil")
	}
}

func Test_GHSA_mmfr_pmjx_hw9w_exposure(t *testing.T) {
	// Same trigger through the application's call pattern using openapi3filter.Options
	spec := &openapi3.T{
		Paths: openapi3.Paths{
			"/test": &openapi3.PathItem{
				Post: &openapi3.Operation{
					RequestBody: &openapi3.RequestBodyRef{
						Value: &openapi3.RequestBody{
							Content: openapi3.Content{
								"multipart/form-data": {
									Schema: &openapi3.SchemaRef{
										Value: openapi3.NewSchemaRef("", &openapi3.Schema{Type: "object"}),
									},
								},
							},
						},
					},
				},
			},
		},
	}

	options := openapi3filter.Options{}
	req := httptest.NewRequest("POST", "http://example.com/test", strings.NewReader("--boundary\r\nmalformed"))
	req.Header.Set("Content-Type", "multipart/form-data; boundary=boundary")

	var body interface{}
	_, err := openapi3filter.DecodeRequest(&body, req, "/test", "POST", spec, &options)

	if err == nil {
		t.Fatalf("expected error from malformed multipart/form-data, got nil")
	}
}
