"""Generated by ai-test-harness (agent mode) for python-jose 3.4.0 (category: cve, issue CVE-2024-29370).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import zlib

import pytest

from jose import jwe
from jose.exceptions import JWEError

KEY = "asecret128bitkey"


def _make_token():
    """Build a valid compressed JWE token whose plaintext is small."""
    plaintext = b"hello world" * 10
    return jwe.encrypt(plaintext, KEY, algorithm="dir", encryption="A128GCM", zip="DEF")


def test_pysec_2025_185_fix_pinning():
    """jwe.decrypt must reject a JWE string longer than the size limit (JWEError)."""
    token = _make_token()
    # Pad the ciphertext segment with base64url 'A' so the string exceeds the
    # 250 KiB limit; the new version rejects it before any decompression.
    parts = token.split(".")
    parts[3] = parts[3] + "A" * (260 * 1024)
    oversized = ".".join(parts)
    assert len(oversized) > 250 * 1024
    with pytest.raises(JWEError):
        jwe.decrypt(oversized, KEY)


def test_pysec_2025_185_exposure():
    """Same oversized-token trigger as an application would pass to jwe.decrypt."""
    token = _make_token()
    parts = token.split(".")
    parts[3] = parts[3] + "A" * (260 * 1024)
    oversized = ".".join(parts)
    with pytest.raises(JWEError):
        jwe.decrypt(oversized, KEY)
    # Sanity: a normal token still decrypts fine.
    assert jwe.decrypt(token, KEY) == b"hello world" * 10
