"""Generated by ai-test-harness (agent mode) for pyasn1 0.4.8 (category: cve, issue CVE-2026-30922).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import pytest
from pyasn1.codec.ber import decoder
from pyasn1.error import PyAsn1Error


def _build_nested_sequence(depth):
    # Build a BER-encoded SEQUENCE nested `depth` levels deep.
    # Each level: 0x30 (constructed SEQUENCE) + length + inner content.
    inner = b'\x05\x00'  # NULL
    for _ in range(depth):
        if len(inner) < 128:
            inner = b'\x30' + bytes([len(inner)]) + inner
        else:
            ln = len(inner)
            if ln <= 0xFF:
                inner = b'\x30\x81' + bytes([ln]) + inner
            else:
                inner = b'\x30\x82' + bytes([(ln >> 8) & 0xFF, ln & 0xFF]) + inner
    return inner


def test_ghsa_jr27_m4p2_rc6r_fix_pinning():
    """Deeply nested SEQUENCE payload must be rejected with PyAsn1Error on the fixed version (0.6.4) instead of recursing unboundedly (RecursionError) on 0.4.8."""
    payload = _build_nested_sequence(5000)
    with pytest.raises(PyAsn1Error):
        decoder.decode(payload)


def test_ghsa_jr27_m4p2_rc6r_exposure():
    """Same deep-nesting trigger via the public ber decoder.decode entry point used by applications: fixed version raises PyAsn1Error, vulnerable version hits RecursionError."""
    payload = _build_nested_sequence(5000)
    with pytest.raises(PyAsn1Error):
        decoder.decode(payload)
