"""Generated by ai-test-harness (agent mode) for pyasn1 0.4.8 (category: cve, issue CVE-2026-59885).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import pytest
from pyasn1.codec.ber import decoder as ber_decoder
from pyasn1.error import PyAsn1Error
from pyasn1.type import univ

def _decode_oid(payload):
    if hasattr(ber_decoder, 'StreamingDecoder'):
        return ber_decoder.StreamingDecoder().decode(payload, asn1Spec=univ.ObjectIdentifier())[0]
    return ber_decoder.decode(payload, asn1Spec=univ.ObjectIdentifier())[0]

def test_ghsa_8ppf_4f7h_5ppj_fix_pinning():
    """Decoding an OID with an arc of >20 continuation octets must raise PyAsn1Error in fixed 0.6.4; vulnerable 0.4.8 accepts it."""
    arc = b'\x80' * 20 + b'\x01'
    body = b'\x00' + arc * 30
    payload = b'\x06' + bytes([len(body)]) + body
    with pytest.raises(PyAsn1Error):
        _decode_oid(payload)

def test_ghsa_8ppf_4f7h_5ppj_exposure():
    """Same trigger via the application's call pattern (ber decoder decode of an ObjectIdentifier) must raise PyAsn1Error in fixed 0.6.4."""
    arc = b'\x80' * 20 + b'\x01'
    body = b'\x00' + arc * 30
    payload = b'\x06' + bytes([len(body)]) + body
    with pytest.raises(PyAsn1Error):
        _decode_oid(payload)
