"""Generated by ai-test-harness (agent mode) for starlette 0.41.3 (category: cve, issue CVE-2026-54283).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import pytest
import httpx
from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import PlainTextResponse


def make_app():
    async def endpoint(request: Request):
        form = await request.form(max_fields=5)
        return PlainTextResponse(str(len(form)))

    app = Starlette()
    app.add_route("/form", endpoint, methods=["POST"])
    return app


@pytest.mark.anyio
async def test_ghsa_82w8_qh3p_5jfq_fix_pinning():
    """urlencoded form(max_fields=5) must reject 50 fields (400) instead of silently ignoring the limit."""
    app = make_app()
    body = "&".join(f"key{i}=v" for i in range(50))
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        resp = await client.post(
            "/form",
            content=body,
            headers={"Content-Type": "application/x-www-form-urlencoded"},
        )
    assert resp.status_code == 400, f"expected 400, got {resp.status_code}"


@pytest.mark.anyio
async def test_ghsa_82w8_qh3p_5jfq_exposure():
    """app-style request.form(max_fields=...) on urlencoded must be enforced, not silently ignored."""
    app = make_app()
    body = "&".join(f"key{i}=v" for i in range(50))
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        resp = await client.post(
            "/form",
            content=body,
            headers={"Content-Type": "application/x-www-form-urlencoded"},
        )
    assert resp.status_code == 400, f"expected 400, got {resp.status_code}"
