"""Generated by ai-test-harness (agent mode) for starlette 0.41.3 (category: cve, issue CVE-2026-48817).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import asyncio

from starlette.endpoints import HTTPEndpoint
from starlette.responses import PlainTextResponse


def make_scope(method):
    return {
        "type": "http",
        "method": method,
        "path": "/",
        "headers": [],
        "query_string": b"",
        "root_path": "",
        "scheme": "http",
        "server": ("testserver", 80),
        "client": ("testclient", 123),
    }


class ProbeEndpoint(HTTPEndpoint):
    def get(self, request):
        return PlainTextResponse("ok")

    def trace(self, request):
        return PlainTextResponse("secret-trace")


def capture_response():
    sent = []

    async def receive():
        return {"type": "http.request", "body": b"", "more_body": False}

    async def send(message):
        sent.append(message)

    return sent, receive, send


def run_endpoint(method):
    sent, receive, send = capture_response()
    endpoint = ProbeEndpoint(make_scope(method), receive, send)
    asyncio.get_event_loop().run_until_complete(endpoint.dispatch())
    return sent


def test_ghsa_x746_7m8f_x49c_fix_pinning():
    """Non-standard HTTP method must not be dispatched to an arbitrary endpoint attribute (CVE-2026-48817)."""
    sent = run_endpoint("TRACE")
    status = next(m["status"] for m in sent if m["type"] == "http.response.start")
    assert status == 405, f"expected 405 for TRACE, got {status}"


def test_ghsa_x746_7m8f_x49c_exposure():
    """Same trigger via the app's dispatch call pattern: dispatch() must not call the arbitrary handler."""
    sent = run_endpoint("TRACE")
    body = b"".join(m.get("body", b"") for m in sent if m["type"] == "http.response.body")
    assert b"secret-trace" not in body, "arbitrary attribute handler was invoked"
