"""Generated by ai-test-harness (agent mode) for starlette 0.41.3 (category: cve, issue CVE-2026-54282).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import pytest
from starlette.datastructures import URL

POISON = "@evil.com"


def _scope(path):
    return {
        "type": "http",
        "method": "GET",
        "scheme": "https",
        "server": ("testserver", 443),
        "path": path,
        "query_string": b"",
        "headers": [],
    }


def test_ghsa_jp82_jpqv_5vv3_fix_pinning():
    """A request path not starting with '/' must not poison request.url.hostname (GHSA-jp82-jpqv-5vv3)."""
    url = URL(scope=_scope(POISON))
    assert url.hostname == "testserver"
    assert url.path == POISON


def test_ghsa_jp82_jpqv_5vv3_exposure():
    """Same trigger via the app's BaseHTTPMiddleware dispatch pattern: request.url.hostname stays the server host."""
    from starlette.requests import Request

    request = Request(_scope(POISON))
    assert request.url.hostname == "testserver"
    assert request.url.path == POISON
