"""Generated by ai-test-harness (agent mode) for starlette 0.41.3 (category: cve, issue CVE-2025-62727).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import time

from starlette.responses import FileResponse


def _build_range_header(n: int, file_size: int) -> str:
    # n overlapping ranges, each covering the whole file -> worst case for merging
    parts = [f"0-{file_size - 1}" for _ in range(n)]
    return "bytes=" + ",".join(parts)


def test_ghsa_7f5h_v6xp_fcq8_fix_pinning():
    """O(n^2) DoS: many overlapping ranges in a Range header must be parsed in bounded time."""
    file_size = 1000
    n = 100000
    header = _build_range_header(n, file_size)
    start = time.perf_counter()
    ranges = FileResponse._parse_range_header(header, file_size)
    elapsed = time.perf_counter() - start
    assert elapsed < 2.0, f"range parsing took {elapsed:.2f}s (O(n^2) DoS)"
    assert ranges == [(0, file_size)]


def test_ghsa_7f5h_v6xp_fcq8_exposure(tmp_path):
    """Same trigger through the ASGI call path the app uses (FileResponse with a Range header)."""
    import anyio

    file_size = 1000
    n = 100000
    header = _build_range_header(n, file_size)
    path = tmp_path / "blob.bin"
    path.write_bytes(b"A" * file_size)

    async def main():
        messages = []

        async def send(message):
            messages.append(message)

        scope = {
            "type": "http",
            "method": "GET",
            "headers": [(b"range", header.encode("latin-1"))],
        }

        async def receive():
            return {"type": "http.request", "body": b"", "more_body": False}

        start = time.perf_counter()
        await FileResponse(str(path))(scope, receive, send)
        elapsed = time.perf_counter() - start
        return elapsed, messages

    elapsed, messages = anyio.run(main)
    assert elapsed < 2.0, f"request handling took {elapsed:.2f}s (O(n^2) DoS)"
    assert messages[0]["status"] == 206
