"""Generated by ai-test-harness (agent mode) for starlette 0.41.3 (category: cve, issue CVE-2025-54121).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json.
"""
import asyncio
import pytest
from starlette.datastructures import Headers
from starlette.formparsers import MultiPartParser, MultiPartException


def _body(size: int) -> bytes:
    head = (
        b"------testboundary\r\n"
        b'Content-Disposition: form-data; name="file"; filename="big.bin"\r\n'
        b"Content-Type: application/octet-stream\r\n\r\n"
    )
    tail = b"\r\n------testboundary--\r\n"
    return head + (b"A" * size) + tail


def _stream(body: bytes):
    async def gen():
        yield body
    return gen()


def _headers() -> Headers:
    return Headers(raw=[(b"content-type", b"multipart/form-data; boundary=----testboundary")])


def _parse(body: bytes):
    parser = MultiPartParser(_headers(), _stream(body))
    return asyncio.run(parser.parse())


def test_GHSA_2c2j_9gv5_cj73_fix_pinning():
    """A multipart file upload larger than the 1MB file limit must be rejected
    with MultiPartException on the fixed version (0.41.3 accepts it, a DoS vector)."""
    with pytest.raises(MultiPartException):
        _parse(_body(2 * 1024 * 1024))


def test_GHSA_2c2j_9gv5_cj73_exposure():
    """Same oversized multipart body through the app's request.form() call path
    must not succeed on the fixed version."""
    with pytest.raises(MultiPartException):
        _parse(_body(2 * 1024 * 1024))
